### PR TITLE
Fix filename collision on case-insensitive filesystems

### PR DESCRIPTION
**Pull request by dennis-kuypers-gcx**

### CODE REVIEW

**Comment by stoiveyp** [comment]
IF you pull from my master you'll see this has already been fixed, as it caused a problem with GitHub actions - I couldn't have release 5.4.1 without it being fixed.

**Comment by dennis-kuypers-gcx** [comment]
I believe this not to be the case. Checking out your master leaves me with a small-case interactionModel.json
Also the file listing shows it at the bottom of the list.

https://github.com/stoiveyp/Alexa.NET.Management/tree/master/Tests/Alexa.NET.Management.Tests/Examples

**Comment by stoiveyp** [comment]
I'm afraid you're mistaken. If you don't have InteractionModel.json then your GitHub copy is out of date.

Here's the image showing the latest file.
image

and the commit I made to fix the issue earlier
image

and the test that failed that caused me to fix the issue
https://github.com/stoiveyp/Alexa.NET.Management/blob/master/Tests/Alexa.NET.Management.Tests/SkillManifestTests.cs#L53-L56

As I said before - GitHub actions, the system I use to build the NuGet package? It's case-sensitive. If it wasn't correct then you wouldn't have received the fix for the slot types in v5.4.1

Hope this clears everything up.

**Comment by dennis-kuypers-gcx** [comment]
I do have `InteractionModel.json` but I also have a `interactionModel.json` and on my filesystem (which is case-insensitive) It causes problems. I basically have a permanent change in `interactionModel.json` that I can not get rid of, even with `git reset --hard`. My PR removes the lowercase file (and also introduces a newline in `InteractionModel.json` but that shouldn't matter)

```
> git fetch upstream && git reset --hard upstream/master
HEAD is now at 42e9c04 Create InteractionModel.json
> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Tests/Alexa.NET.Management.Tests/Examples/InteractionModel.json

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by stoiveyp** [comment]
Can I ask what the error is you're getting? I run case-insensitive locally without any trouble

**Comment by dennis-kuypers-gcx** [comment]
There is no error with compilation or tests. The problem that i'm having is that I get this permanent change in the interactionmodel file due to the two files sharing the same name on my OS (git status always shows this change)
It would help me (and potentially others?) to have the lowercase file removed :)

**Comment by stoiveyp** [comment]
Ahh ok, when you said "fix" - I assumed something was breaking.
ok - I'll merge this in.

**Pull request merged**
